Feature: Admin menambah riwayat penunjang lain

Background:
        Given "Admin" masuk ke siakad
        * "Admin" masuk ke modul "SDM" 
    
    Scenario: Positif - Menambahkan data dengan benar
        When "Admin" menuju ke halaman "hr/list_rpenunjanglain/1"
        * "Admin" klik tombol "Tambah"        
        * "Admin" mengisi field "Kategori Kegiatan Atas" dengan "Sebagai anggota"
        * "Admin" mengisi field "Jenis Kegiatan" dengan "Sebagai anggota"
        * "Admin" mengisi field "Tingkat" dengan "Lokal"
        * "Admin" mengisi field "Nama Kegiatan" dengan "Perancangan Aset Konten Digital untuk Kegiatan Promosi Agrowisata PT Perkebunan Nusantara VIII"
        * "Admin" mengisi field "Instansi" dengan "Kantor Baru"
        * "Admin" mengisi field "Mulai Keanggotaan" dengan "20-05-2022"
        * "Admin" mengisi field "SK Dropdown" dengan "DED/2023/12/1212"
        * "Admin" mengisi field "Status Pengajuan" dengan "Disetujui"
        * "Admin" mengisi field "iPeran" dengan "Sebagai Anggota"
        * "Admin" klik tombol "Simpan"
        * "Admin" klik tombol "Ya, Yakin"
        Then "Admin" melihat alert "Berhasil"
        * "Admin" melihat data "penunjang lain" ada di list

    Scenario: Positif - Menambahkan data dengan anggota lebih dari 1
        When "Admin" menuju ke halaman "hr/list_rpenunjanglain/1"
        * "Admin" klik tombol "Tambah"        
        * "Admin" mengisi field "Kategori Kegiatan Atas" dengan "Sebagai anggota"
        * "Admin" mengisi field "Jenis Kegiatan" dengan "Sebagai anggota"
        * "Admin" mengisi field "Tingkat" dengan "Lokal"
        * "Admin" mengisi field "Nama Kegiatan" dengan "Perancangan Aset Konten Digital"
        * "Admin" mengisi field "Instansi" dengan "Kantor Baru"
        * "Admin" mengisi field "Mulai Keanggotaan" dengan "20-05-2022"
        * "Admin" mengisi field "SK Dropdown" dengan "DED/2023/12/1212"
        * "Admin" mengisi field "Status Pengajuan" dengan "Disetujui"
        * "Admin" mengisi field "iPeran" dengan "Sebagai Anggota"
        * "Admin" klik tombol "Tambah Anggota"
        * "Admin" mengisi field "Nama Pegawai 2" dengan "suhadi"
        * "Admin" mengisi field "iPeran 2" dengan "Sebagai Anggota"
        * "Admin" klik tombol "Simpan"
        * "Admin" klik tombol "Ya, Yakin"
        Then "Admin" melihat alert "Berhasil"
        Then "Admin" melihat jumlah anggota adalah "2"

    Scenario: Positif - Menambahkan data dengan mengosongkan kategori kegiatan
        When "Admin" menuju ke halaman "hr/list_rpenunjanglain/1"
        * "Admin" klik tombol "Tambah"
        * "Admin" mengisi field "Jenis Kegiatan" dengan "Sebagai anggota"
        * "Admin" mengisi field "Tingkat" dengan "Lokal"
        * "Admin" mengisi field "Nama Kegiatan" dengan "Perancangan Aset Konten Digital untuk Kegiatan Promosi Agrowisata PT Perkebunan Nusantara VIII"
        * "Admin" mengisi field "Instansi" dengan "Kantor Baru"
        * "Admin" mengisi field "Mulai Keanggotaan" dengan "20-05-2022"
        * "Admin" mengisi field "SK Dropdown" dengan "DED/2023/12/1212"
        * "Admin" mengisi field "Status Pengajuan" dengan "Disetujui"
        * "Admin" mengisi field "iPeran" dengan "Sebagai Anggota"
        * "Admin" klik tombol "Simpan"
        * "Admin" klik tombol "Ya, Yakin"
        Then "Admin" melihat modal dengan pesan "Mohon mengisi isian yang bergaris merah"

    Scenario: Positif - Menambahkan data dengan mengosongkan jenis kegiatan
        When "Admin" menuju ke halaman "hr/list_rpenunjanglain/1"
        * "Admin" klik tombol "Tambah"        
        * "Admin" mengisi field "Kategori Kegiatan Atas" dengan "Sebagai anggota"
        * "Admin" mengisi field "Tingkat" dengan "Lokal"
        * "Admin" mengisi field "Nama Kegiatan" dengan "Perancangan Aset Konten Digital untuk Kegiatan Promosi Agrowisata PT Perkebunan Nusantara VIII"
        * "Admin" mengisi field "Instansi" dengan "Kantor Baru"
        * "Admin" mengisi field "Mulai Keanggotaan" dengan "20-05-2022"
        * "Admin" mengisi field "SK Dropdown" dengan "DED/2023/12/1212"
        * "Admin" mengisi field "Status Pengajuan" dengan "Disetujui"
        * "Admin" mengisi field "iPeran" dengan "Sebagai Anggota"
        * "Admin" klik tombol "Simpan"
        * "Admin" klik tombol "Ya, Yakin"
        Then "Admin" melihat modal dengan pesan "Mohon mengisi isian yang bergaris merah"

    Scenario: Positif - Menambahkan data dengan mengosongkan tingkat
        When "Admin" menuju ke halaman "hr/list_rpenunjanglain/1"
        * "Admin" klik tombol "Tambah"        
        * "Admin" mengisi field "Kategori Kegiatan Atas" dengan "Sebagai anggota"
        * "Admin" mengisi field "Jenis Kegiatan" dengan "Sebagai anggota"
        * "Admin" mengisi field "Nama Kegiatan" dengan "Perancangan Aset Konten Digital untuk Kegiatan Promosi Agrowisata PT Perkebunan Nusantara VIII"
        * "Admin" mengisi field "Instansi" dengan "Kantor Baru"
        * "Admin" mengisi field "Mulai Keanggotaan" dengan "20-05-2022"
        * "Admin" mengisi field "SK Dropdown" dengan "DED/2023/12/1212"
        * "Admin" mengisi field "Status Pengajuan" dengan "Disetujui"
        * "Admin" mengisi field "iPeran" dengan "Sebagai Anggota"
        * "Admin" klik tombol "Simpan"
        * "Admin" klik tombol "Ya, Yakin"
        Then "Admin" melihat modal dengan pesan "Mohon mengisi isian yang bergaris merah"

    Scenario: Positif - Menambahkan data dengan mengosongkan nama kegiatan
        When "Admin" menuju ke halaman "hr/list_rpenunjanglain/1"
        * "Admin" klik tombol "Tambah"        
        * "Admin" mengisi field "Kategori Kegiatan Atas" dengan "Sebagai anggota"
        * "Admin" mengisi field "Jenis Kegiatan" dengan "Sebagai anggota"
        * "Admin" mengisi field "Tingkat" dengan "Lokal"
        * "Admin" mengisi field "Instansi" dengan "Kantor Baru"
        * "Admin" mengisi field "Mulai Keanggotaan" dengan "20-05-2022"
        * "Admin" mengisi field "SK Dropdown" dengan "DED/2023/12/1212"
        * "Admin" mengisi field "Status Pengajuan" dengan "Disetujui"
        * "Admin" mengisi field "iPeran" dengan "Sebagai Anggota"
        * "Admin" klik tombol "Simpan"
        * "Admin" klik tombol "Ya, Yakin"
        Then "Admin" melihat modal dengan pesan "Mohon mengisi isian yang bergaris merah"

    Scenario: Positif - Menambahkan data dengan mengosongkan instansi
        When "Admin" menuju ke halaman "hr/list_rpenunjanglain/1"
        * "Admin" klik tombol "Tambah"        
        * "Admin" mengisi field "Kategori Kegiatan Atas" dengan "Sebagai anggota"
        * "Admin" mengisi field "Jenis Kegiatan" dengan "Sebagai anggota"
        * "Admin" mengisi field "Tingkat" dengan "Lokal"
        * "Admin" mengisi field "Nama Kegiatan" dengan "Perancangan Aset Konten Digital untuk Kegiatan Promosi Agrowisata PT Perkebunan Nusantara VIII"
        * "Admin" mengisi field "Mulai Keanggotaan" dengan "20-05-2022"
        * "Admin" mengisi field "SK Dropdown" dengan "DED/2023/12/1212"
        * "Admin" mengisi field "Status Pengajuan" dengan "Disetujui"
        * "Admin" mengisi field "iPeran" dengan "Sebagai Anggota"
        * "Admin" klik tombol "Simpan"
        * "Admin" klik tombol "Ya, Yakin"
        Then "Admin" melihat modal dengan pesan "Mohon mengisi isian yang bergaris merah"

    Scenario: Positif - Menambahkan data dengan mengosongkan tanggal mulai
        When "Admin" menuju ke halaman "hr/list_rpenunjanglain/1"
        * "Admin" klik tombol "Tambah"        
        * "Admin" mengisi field "Kategori Kegiatan Atas" dengan "Sebagai anggota"
        * "Admin" mengisi field "Jenis Kegiatan" dengan "Sebagai anggota"
        * "Admin" mengisi field "Tingkat" dengan "Lokal"
        * "Admin" mengisi field "Nama Kegiatan" dengan "Perancangan Aset Konten Digital untuk Kegiatan Promosi Agrowisata PT Perkebunan Nusantara VIII"
        * "Admin" mengisi field "Instansi" dengan "Kantor Baru"
        * "Admin" mengisi field "SK Dropdown" dengan "DED/2023/12/1212"
        * "Admin" mengisi field "Status Pengajuan" dengan "Disetujui"
        * "Admin" mengisi field "iPeran" dengan "Sebagai Anggota"
        * "Admin" klik tombol "Simpan"
        * "Admin" klik tombol "Ya, Yakin"
        Then "Admin" melihat modal dengan pesan "Mohon mengisi isian yang bergaris merah"

    Scenario: Positif - Menambahkan data dengan mengosongkan sk
        When "Admin" menuju ke halaman "hr/list_rpenunjanglain/1"
        * "Admin" klik tombol "Tambah"        
        * "Admin" mengisi field "Kategori Kegiatan Atas" dengan "Sebagai anggota"
        * "Admin" mengisi field "Jenis Kegiatan" dengan "Sebagai anggota"
        * "Admin" mengisi field "Tingkat" dengan "Lokal"
        * "Admin" mengisi field "Nama Kegiatan" dengan "Perancangan Aset Konten Digital untuk Kegiatan Promosi Agrowisata PT Perkebunan Nusantara VIII"
        * "Admin" mengisi field "Instansi" dengan "Kantor Baru"
        * "Admin" mengisi field "Mulai Keanggotaan" dengan "20-05-2022"
        * "Admin" mengisi field "Status Pengajuan" dengan "Disetujui"
        * "Admin" mengisi field "iPeran" dengan "Sebagai Anggota"
        * "Admin" klik tombol "Simpan"
        * "Admin" klik tombol "Ya, Yakin"
        Then "Admin" melihat modal dengan pesan "Mohon mengisi isian yang bergaris merah"

    Scenario: Positif - Menambahkan data dengan mengosongkan peran
        When "Admin" menuju ke halaman "hr/list_rpenunjanglain/1"
        * "Admin" klik tombol "Tambah"        
        * "Admin" mengisi field "Kategori Kegiatan Atas" dengan "Sebagai anggota"
        * "Admin" mengisi field "Jenis Kegiatan" dengan "Sebagai anggota"
        * "Admin" mengisi field "Tingkat" dengan "Lokal"
        * "Admin" mengisi field "Nama Kegiatan" dengan "Perancangan Aset Konten Digital untuk Kegiatan Promosi Agrowisata PT Perkebunan Nusantara VIII"
        * "Admin" mengisi field "Instansi" dengan "Kantor Baru"
        * "Admin" mengisi field "Mulai Keanggotaan" dengan "20-05-2022"
        * "Admin" mengisi field "SK Dropdown" dengan "DED/2023/12/1212"
        * "Admin" mengisi field "Status Pengajuan" dengan "Disetujui"
        * "Admin" klik tombol "Simpan"
        * "Admin" klik tombol "Ya, Yakin"
        Then "Admin" melihat modal dengan pesan "Mohon mengisi isian yang bergaris merah"